version: "2"
checks:
  complex-logic:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 500
exclude_patterns:
- "test/"
- "docs/"
