version: "2"
checks:
  complex-logic:
    config:
      threshold: 20
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 800
  similar-code:
    config:
      threshold: 40
  identical-code:
    config:
      threshold: 40
exclude_patterns:
- "test/"
- "docs/"
